# time parmaeters
min_time: -2.0
max_time: 0.5
n_time: 20
log_time: True

n_runs: 100  # number of Louvain runs
n_workers: 2  # number of workers for parallel computing

# quality constructor
#constructor: 'continuous_combinatorial'
constructor: 'continuous_linearized'
#constructor: 'continuous_normalized'
#constructor: 'signed_modularity'

# additional parameters
compute_mutual_information: True 
n_partitions: 20  # number of louvian runs for MI computation
compute_ttprime: True
apply_postprocessing: False #True



