# time parmaeters
min_time: -2.0
max_time: 0.5
n_time: 10
log_time: True

n_runs: 20  # number of Louvain runs
n_workers: 2  # number of workers for parallel computing

constructor: 'continuous_combinatorial'  # quality constructor
#constructor: 'continuous_linearized'  # quality constructor
#constructor: 'continuous_normalized'  # quality constructor

# additional parameters
save_qualities: True 
compute_mutual_information: True 
n_partitions: 20  # number of louvian runs for MI computation
compute_ttprime: True
apply_postprocessing: True



