# time parmaeters
min_time: -3.
max_time: 0.5
n_time: 20
log_time: True

n_runs: 50  # number of Louvain runs
n_workers: 4  # number of workers for parallel computing

constructor: 'continuous_combinatorial'  # quality constructor

# additional parameters
save_qualities: True
compute_mutual_information: True
n_partitions: 10  # number of louvian runs for MI computation
compute_ttprime: True
apply_postprocessing: = True



